#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
  path: /
  controller: App\Controller\HomeController::index

homepage_connected:
  path: /logged/
  controller: App\Controller\IController::index

filtre:
  path: /logged/{info}
  controller: App\Controller\IController::itest
  defaults:
    info : "Oui"

document_add:
  path: /add/
  controller: App\Controller\AddController::add

show_pdf:
  path: /pdf/{name}
  controller: App\Controller\HomeController::show

app_stats:
  path: /stats/
  controller: App\Controller\IController::stats


